# Generated by Django 5.0.7 on 2024-08-04 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='Zipcode',
            new_name='zipcode',
        ),
    ]
